POW_DIGITS = 2

PROTOCOL_VERSION = b"!not(OSX<LinuX)"
assert len(PROTOCOL_VERSION) <= 16
PROTOCOL_VERSION = (bytes(16) + PROTOCOL_VERSION)[-16:]

PORT = 3514
BROADPORT = 5252
VERBOSE = False

MSGDIR = "msgs/"
LISTEN_FOR_BROADCASTS = True
CREATE_BROADCASTS = True
